### ISSUE TITLE
Implement persistence images

### ISSUE THREAD

**Issue by rrrlw** [tdaverse/ggtda#18]
Introduced in [this JMLR article](https://www.jmlr.org/papers/v18/16-337.html)

**Comment by corybrunson** [comment]
Something to consider for the broader tdaverse is a standalone package for vectorizations of persistence data. These might include
* persistence images
* [persistence landscapes](https://www.sciencedirect.com/science/article/pii/S0747717116300104) (though these might warrant a standalone package)
* [persistence rank function](https://www.sciencedirect.com/science/article/pii/S0097849320300893)
* @rrrlw [your own use of dimension-wise first moments](https://aapm.onlinelibrary.wiley.com/doi/abs/10.1002/mp.15255)

I mention this because it would save {ggtda} a lot of code without introducing dependencies; the user would generate the vectorizations externally, but then {ggtda} would know how to visualize them.

Once done, it would be quick and valuable to provide a [{recipes} extension](https://www.tidyverse.org/blog/2022/05/recipes-update-05-20222/) for these vectorizations. Building a recipes extension is like building a {ggplot2} extension, only more so. I made [a small one for association rules](https://github.com/corybrunson/arulesteps), and [{embed}](https://github.com/tidymodels/embed) is a great point of reference.

**Comment by corybrunson** [comment]
Subsumed into #54.
